language: python
dist: bionic
install:
  - pip install --upgrade pip
  - pip install .
  - wget https://github.com/embree/embree/releases/download/v3.13.2/embree-3.13.2.x86_64.linux.tar.gz
  - tar xvf embree-3.13.2.x86_64.linux.tar.gz
  - cd embree-3.13.2.x86_64.linux.tar.gz
  - sh embree-vars.sh
script:
  - python -m unittest
