name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_SKIP: pp* *-win32
      CIBW_TEST_REQUIRES: pytest numpy
      CIBW_TEST_COMMAND: pytest -v {project}/tests
      CIBW_BEFORE_BUILD_LINUX: "yum install -y cmake glfw-devel wget; pip install cython; bash {project}/ci/embree3.bash; source ~/embree/embree_vars.sh"
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'
    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==2.3.1
    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
    - name: Upload To PyPi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      # TODO : remove `if false` statement after secrets are set in Github UI
      if: false
      run: |
        pip install twine
        twine upload ./wheelhouse/*
